### ISSUE TITLE
链接oracle数据库出错

### ISSUE THREAD

**Issue by ThinkPeace** [pingfangushi/screw#21]
"C:\Program Files\Java\jdk1.8.0_202\bin\java.exe" -Dmaven.multiModuleProjectDirectory=E:\screw -Dmaven.home=D:\SmartHS5Develop\apache-maven-3.5.3 -Dclassworlds.conf=D:\SmartHS5Develop\apache-maven-3.5.3\bin\m2.conf -Dmaven.ext.class.path=D:\ideaIU-2019.2.3.win\plugins\maven\lib\maven-event-listener.jar -javaagent:D:\ideaIU-2019.2.3.win\lib\idea_rt.jar=52695:D:\ideaIU-2019.2.3.win\bin -Dfile.encoding=GBK -classpath D:\SmartHS5Develop\apache-maven-3.5.3\boot\plexus-classworlds-2.5.2.jar org.codehaus.classworlds.Launcher -Didea.version2019.2.3 -s D:\SmartHS5Develop\apache-maven-3.5.3\conf\settings.xml -Dmaven.repo.local=D:\java\maven\repository cn.smallbun.screw:screw-maven-plugin:1.0.3:run
[INFO] Scanning for projects...
[INFO] 
[INFO] -------------------------< com.example:screw >--------------------------
[INFO] Building screw 0.0.1-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- screw-maven-plugin:1.0.3:run (default-cli) @ screw ---
[INFO] Database design document generation begins ?
[INFO] screw - Starting...
[INFO] screw - Driver does not support get/set network timeout for connections. (oracle.jdbc.driver.T4CConnection.getNetworkTimeout()I)
[INFO] screw - Start completed.
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 0.959 s
[INFO] Finished at: 2020-10-19T15:51:31+08:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal cn.smallbun.screw:screw-maven-plugin:1.0.3:run (default-cli) on project screw: Execution default-cli of goal cn.smallbun.screw:screw-maven-plugin:1.0.3:run failed: An API incompatibility was encountered while executing cn.smallbun.screw:screw-maven-plugin:1.0.3:run: java.lang.AbstractMethodError: oracle.jdbc.driver.T4CConnection.getSchema()Ljava/lang/String;
[ERROR] -----------------------------------------------------
[ERROR] realm =    plugin>cn.smallbun.screw:screw-maven-plugin:1.0.3
[ERROR] strategy = org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy
[ERROR] urls[0] = file:/D:/java/maven/repository/cn/smallbun/screw/screw-maven-plugin/1.0.3/screw-maven-plugin-1.0.3.jar
[ERROR] urls[1] = file:/D:/java/maven/repository/com/zaxxer/HikariCP/3.4.5/HikariCP-3.4.5.jar
[ERROR] urls[2] = file:/D:/java/maven/repository/com/oracle/database/jdbc/ojdbc6/11.2.0.4/ojdbc6-11.2.0.4.jar
[ERROR] urls[3] = file:/D:/java/maven/repository/com/oracle/database/jdbc/ucp/11.2.0.4/ucp-11.2.0.4.jar
[ERROR] urls[4] = file:/D:/java/maven/repository/com/oracle/database/security/oraclepki/11.2.0.4/oraclepki-11.2.0.4.jar
[ERROR] urls[5] = file:/D:/java/maven/repository/com/oracle/database/security/osdt_cert/11.2.0.4/osdt_cert-11.2.0.4.jar
[ERROR] urls[6] = file:/D:/java/maven/repository/com/oracle/database/security/osdt_core/11.2.0.4/osdt_core-11.2.0.4.jar
[ERROR] urls[7] = file:/D:/java/maven/repository/com/oracle/database/ha/simplefan/11.2.0.4/simplefan-11.2.0.4.jar
[ERROR] urls[8] = file:/D:/java/maven/repository/com/oracle/database/ha/ons/11.2.0.4/ons-11.2.0.4.jar
[ERROR] urls[9] = file:/D:/java/maven/repository/cn/smallbun/screw/screw-core/1.0.3/screw-core-1.0.3.jar
[ERROR] urls[10] = file:/D:/java/maven/repository/commons-lang/commons-lang/2.6/commons-lang-2.6.jar
[ERROR] urls[11] = file:/D:/java/maven/repository/commons-logging/commons-logging/1.2/commons-logging-1.2.jar
[ERROR] urls[12] = file:/D:/java/maven/repository/org/freemarker/freemarker/2.3.30/freemarker-2.3.30.jar
[ERROR] urls[13] = file:/D:/java/maven/repository/ch/qos/logback/logback-classic/1.2.3/logback-classic-1.2.3.jar
[ERROR] urls[14] = file:/D:/java/maven/repository/ch/qos/logback/logback-core/1.2.3/logback-core-1.2.3.jar
[ERROR] urls[15] = file:/D:/java/maven/repository/com/alibaba/fastjson/1.2.72/fastjson-1.2.72.jar
[ERROR] urls[16] = file:/D:/java/maven/repository/org/apache/commons/commons-lang3/3.8.1/commons-lang3-3.8.1.jar
[ERROR] urls[17] = file:/D:/java/maven/repository/javax/enterprise/cdi-api/1.0/cdi-api-1.0.jar
[ERROR] urls[18] = file:/D:/java/maven/repository/org/eclipse/sisu/org.eclipse.sisu.inject/0.3.4/org.eclipse.sisu.inject-0.3.4.jar
[ERROR] urls[19] = file:/D:/java/maven/repository/org/codehaus/plexus/plexus-component-annotations/1.5.5/plexus-component-annotations-1.5.5.jar
[ERROR] urls[20] = file:/D:/java/maven/repository/org/codehaus/plexus/plexus-utils/3.2.1/plexus-utils-3.2.1.jar
[ERROR] Number of foreign imports: 1
[ERROR] import: Entry[import  from realm ClassRealm[maven.api, parent: null]]
[ERROR] 
[ERROR] -----------------------------------------------------
[ERROR] 
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginContainerException

**Comment by JeyiJeyi** [comment]
+1，链接oracle会出错
java.lang.AbstractMethodError: null
	at com.zaxxer.hikari.pool.HikariProxyConnection.getSchema(HikariProxyConnection.java) ~[HikariCP-3.4.5.jar:na]
	at cn.smallbun.screw.core.query.AbstractDatabaseQuery.getSchema(AbstractDatabaseQuery.java:118) ~[screw-core-1.0.5.jar:na]
	at cn.smallbun.screw.core.query.oracle.OracleDataBaseQuery.getDataBase(OracleDataBaseQuery.java:84) ~[screw-core-1.0.5.jar:na]
	at cn.smallbun.screw.core.process.DataModelProcess.process(DataModelProcess.java:79) ~[screw-core-1.0.5.jar:na]
	at cn.smallbun.screw.core.execute.DocumentationExecute.execute(DocumentationExecute.java:50) ~[screw-core-1.0.5.jar:na]
	at com.jeyi.springboot.demo.controller.DataBaseController.elearning(DataBaseController.java:125) ~[classes/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_144]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_144]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_144]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_144]
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:190) ~[spring-web-5.2.9.RELEASE.jar:5.2.9.RELEASE]
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:138) ~[spring-web-5.2.9.RELEASE.jar:5.2.9.RELEASE]
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:105) ~[spring-webmvc-5.2.9.RELEASE.jar:5.2.9.RELEASE]
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:878) ~[spring-webmvc-5.2.9.RELEASE.jar:5.2.9.RELEASE]
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:792) ~[spring-webmvc-5.2.9.RELEASE.jar:5.2.9.RELEASE]
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87) ~[spring-webmvc-5.2.9.RELEASE.jar:5.2.9.RELEASE]
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1040) ~[spring-webmvc-5.2.9.RELEASE.jar:5.2.9.RELEASE]
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:943) ~[spring-webmvc-5.2.9.RELEASE.jar:5.2.9.RELEASE]
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006) ~[spring-webmvc-5.2.9.RELEASE.jar:5.2.9.RELEASE]
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:898) ~[spring-webmvc-5.2.9.RELEASE.jar:5.2.9.RELEASE]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:626) ~[tomcat-embed-core-9.0.38.jar:4.0.FR]
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883) ~[spring-webmvc-5.2.9.RELEASE.jar:5.2.9.RELEASE]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:733) ~[tomcat-embed-core-9.0.38.jar:4.0.FR]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231) ~[tomcat-embed-core-9.0.38.jar:9.0.38]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-9.0.38.jar:9.0.38]
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53) ~[tomcat-embed-websocket-9.0.38.jar:9.0.38]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[tomcat-embed-core-9.0.38.jar:9.0.38]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-9.0.38.jar:9.0.38]
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100) ~[spring-web-5.2.9.RELEASE.jar:5.2.9.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) ~[spring-web-5.2.9.RELEASE.jar:5.2.9.RELEASE]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[tomcat-embed-core-9.0.38.jar:9.0.38]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-9.0.38.jar:9.0.38]
	at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93) ~[spring-web-5.2.9.RELEASE.jar:5.2.9.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) ~[spring-web-5.2.9.RELEASE.jar:5.2.9.RELEASE]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[tomcat-embed-core-9.0.38.jar:9.0.38]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-9.0.38.jar:9.0.38]
	at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.doFilterInternal(WebMvcMetricsFilter.java:109) ~[spring-boot-actuator-2.2.10.RELEASE.jar:2.2.10.RELEASE]

**Comment by JeyiJeyi** [comment]
java.lang.AbstractMethodError: oracle.jdbc.driver.T4CConnection.getSchema()Ljava/lang/String;

这是因为oracle驱动版本过低造成的，删除或屏蔽目前驱动版本，驱动添加升级为以下版本：

<dependency>
   <groupId>com.oracle.ojdbc</groupId>
   <artifactId>ojdbc8</artifactId>
   <version>19.3.0.0</version>
</dependency>
<dependency>
   <groupId>cn.easyproject</groupId>
   <artifactId>orai18n</artifactId>
   <version>12.1.0.2.0</version>
</dependency>
