### ISSUE TITLE
支持pg分区表

### ISSUE THREAD

**Issue by hymanchengo** [pingfangushi/screw#33]
是否可以支持pg分区表

**Comment by jiafeimao12** [comment]
pg我都没有跑起来
Exception in thread "main" cn.smallbun.screw.core.exception.ScrewException: java.lang.NullPointerException
	at cn.smallbun.screw.core.util.ExceptionUtils.mpe(ExceptionUtils.java:62)
	at cn.smallbun.screw.core.execute.DocumentationExecute.execute(DocumentationExecute.java:57)
	at org.example.App.main(App.java:84)
Caused by: java.lang.NullPointerException
	at java.util.concurrent.ConcurrentHashMap.putVal(ConcurrentHashMap.java:1011)
	at java.util.concurrent.ConcurrentHashMap.put(ConcurrentHashMap.java:1006)
	at cn.smallbun.screw.core.process.DataModelProcess.process(DataModelProcess.java:104)
	at cn.smallbun.screw.core.execute.DocumentationExecute.execute(DocumentationExecute.java:50)
	... 1 more
