### ISSUE TITLE
好像只支持HikariDataSource，能支持DruidDataSource吗？

### ISSUE THREAD

**Issue by chentianming11** [pingfangushi/screw#4]
好像只支持HikariDataSource，能支持DruidDataSource吗？

**Comment by pingfangushi** [comment]
因为使用了DataSource接口，所以你可以使用任何扩展了DataSource接口的数据源

**Comment by chentianming11** [comment]
cn.smallbun.screw.core.exception.ScrewException: java.lang.ClassCastException: com.lianjia.infrastructure.datasource.druid.DruidDataSourceWrapper cannot be cast to com.zaxxer.hikari.HikariDataSource
	at cn.smallbun.screw.core.util.ExceptionUtils.mpe(ExceptionUtils.java:62)
	at cn.smallbun.screw.core.execute.DocumentationExecute.execute(DocumentationExecute.java:57)
	at com.ke.jiaoyi.helicarrier.base.datasource.DatabaseDocGenerator.onApplicationEvent(DatabaseDocGenerator.java:56)
	at com.ke.jiaoyi.helicarrier.base.datasource.DatabaseDocGenerator.onApplicationEvent(DatabaseDocGenerator.java:22)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:172)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:165)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:402)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:359)
	at org.springframework.boot.context.event.EventPublishingRunListener.running(EventPublishingRunListener.java:103)
	at org.springframework.boot.SpringApplicationRunListeners.running(SpringApplicationRunListeners.java:77)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:327)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1215)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1204)
	at com.ke.jiaoyi.helicarrier.HelicarrierApplication.main(HelicarrierApplication.java:101)
Caused by: java.lang.ClassCastException: com.lianjia.infrastructure.datasource.druid.DruidDataSourceWrapper cannot be cast to com.zaxxer.hikari.HikariDataSource
	at cn.smallbun.screw.core.query.AbstractDatabaseQuery.getSchema(AbstractDatabaseQuery.java:111)
	at cn.smallbun.screw.core.query.mysql.MySqlDataBaseQuery.getTables(MySqlDataBaseQuery.java:84)
	at cn.smallbun.screw.core.process.DataModelProcess.process(DataModelProcess.java:85)
	at cn.smallbun.screw.core.execute.DocumentationExecute.execute(DocumentationExecute.java:50)
	... 13 common frames omitted
那感觉是有bug，我注入我们自己封装的数据源会报错，自己封装的继承了DruidDataSource

**Comment by chentianming11** [comment]
![image](https://user-images.githubusercontent.com/30620547/89285293-ac1e9780-d682-11ea-8dfe-e0270e59d894.png)
