### ISSUE TITLE
postgress NullPointerException

### ISSUE THREAD

**Issue by wangxufire** [pingfangushi/screw#43]
Caused by: java.lang.NullPointerException
	at java.base/java.util.concurrent.ConcurrentHashMap.putVal(ConcurrentHashMap.java:1011)
	at java.base/java.util.concurrent.ConcurrentHashMap.put(ConcurrentHashMap.java:1006)
	at cn.smallbun.screw.core.process.DataModelProcess.process(DataModelProcess.java:104)
	at cn.smallbun.screw.core.execute.DocumentationExecute.execute(DocumentationExecute.java:50)

**Comment by wangxufire** [comment]
可以try catcg log 下，能处理几张表处理几张表， 不能处理的跳过

**Comment by wangxufire** [comment]
顺便 SqlServerDataBaseQuery 这个类的报名应该拼错了 弄成 sqlservice 了
