### ISSUE TITLE
postgre数据库信息转换大小写不匹配导致空指针异常

### ISSUE THREAD

**Issue by handsomestWei** [pingfangushi/screw#73]
## screw版本
```
1.0.5
```

## 异常日志
```
Caused by: java.lang.NullPointerException
	at java.util.concurrent.ConcurrentHashMap.putVal(ConcurrentHashMap.java:1011)
	at java.util.concurrent.ConcurrentHashMap.put(ConcurrentHashMap.java:1006)
	at cn.smallbun.screw.core.process.DataModelProcess.process(DataModelProcess.java:104)
```

## 驱动版本
```
postgresql-42.24.0.jar
```

## 调用链
1、`screw`的`cn.smallbun.screw.core.query.postgresql#PostgreSqlDataBaseQuery`方法获取表信息。
2、调用pg驱动postgresql jar的`org.postgresql.jdbc.PgDatabaseMetaData#getTables`方法，但该方法最后将字段自动转换成大写
```
return ((PgResultSet)this.createMetaDataStatement().executeQuery(sql)).upperCaseFieldLabels();
```
3、`screw`的`cn.smallbun.screw.core.mapping.Mapping#convertList`方法将结果集转换为对象`PostgreSqlTableModel`，但由于该对象注解`@MappingField`值为小写，与调用链2产生的大写名称不匹配，导致全部转换为空值
4、最后`screw`在`cn.smallbun.screw.core.process.DataModelProcess#process`取值时空指针异常

**Comment by SummerWindL** [comment]
> ## screw版本
> ```
> 1.0.5
> ```
> 
> ## 异常日志
> ```
> Caused by: java.lang.NullPointerException
> 	at java.util.concurrent.ConcurrentHashMap.putVal(ConcurrentHashMap.java:1011)
> 	at java.util.concurrent.ConcurrentHashMap.put(ConcurrentHashMap.java:1006)
> 	at cn.smallbun.screw.core.process.DataModelProcess.process(DataModelProcess.java:104)
> ```
> 
> ## 驱动版本
> ```
> postgresql-42.24.0.jar
> ```
> 
> ## 调用链
> 1、`screw`的`cn.smallbun.screw.core.query.postgresql#PostgreSqlDataBaseQuery`方法获取表信息。 2、调用pg驱动postgresql jar的`org.postgresql.jdbc.PgDatabaseMetaData#getTables`方法，但该方法最后将字段自动转换成大写
> 
> ```
> return ((PgResultSet)this.createMetaDataStatement().executeQuery(sql)).upperCaseFieldLabels();
> ```
> 
> 3、`screw`的`cn.smallbun.screw.core.mapping.Mapping#convertList`方法将结果集转换为对象`PostgreSqlTableModel`，但由于该对象注解`@MappingField`值为小写，与调用链2产生的大写名称不匹配，导致全部转换为空值 4、最后`screw`在`cn.smallbun.screw.core.process.DataModelProcess#process`取值时空指针异常

在最新的1.0.6-SNAPSHOT版本这个问题已经得到修复，下载最新代码安装本地仓库就好，这个版面貌似他还没发出来

**Comment by Live-or** [comment]
1.0.6-SNAPSHOT版本没发怎么搞，这个bug有没有办法规避

**Comment by DUWENINK** [comment]
the same question
